export default {
  PRIMARY_LIGHT: '',
  PRIMARY: '',
  PRIMARY_DARK: '',
  SECUNDARY_LIGHT: '',
  SECUNDARY: '',
  SECUNDARY_DARK: '',

  WHITE: '#FFFFFF',
  LIGHTER: '#F0F0F0',
  LIGHT: '#E5E5E5',
  REGULAR: '#999999',
  DARK: '#666666',
  DARKER: '#333333',
  DARKEST: '#000000',

  SUCCESS: '',
  FAILURE: '',
  ERROR: '',
  DANGER: '',
  WARNING: '',

}